#!/bin/bash

app_command="dnd2install-installer $@"

EXIT_STATUS=0

if [ "$(id -u)" -eq 0 ]; then
	# user is admin
	${app_command}
	EXIT_STATUS=$?
else
	# user is not admin
	if echo $- | grep "i" >/dev/null 2>&1; then
		# script is running in interactive mode
		su - -c "${app_command}"
		EXIT_STATUS=$?
	else
		# script is running in non-interactive mode
		if [ "$XDG_SESSION_TYPE" = "wayland" ] ; then
			xhost +SI:localuser:root
			pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY ${app_command}
			EXIT_STATUS=$?
			xhost -SI:localuser:root
			xhost
		elif command -v pkexec >/dev/null 2>&1; then
			pkexec ${app_command}
			EXIT_STATUS=$?
		elif command -v sudo >/dev/null 2>&1; then
			x-terminal-emulator -e "sudo ${app_command}"
			EXIT_STATUS=$?
		elif command -v su >/dev/null 2>&1; then
			x-terminal-emulator -e "su - -c '${app_command}'"
			EXIT_STATUS=$?
		else
			x-terminal-emulator -e "echo 'Command must be run as root user: ${app_command}'"
			EXIT_STATUS=$?
		fi
	fi
fi

exit $EXIT_STATUS
